# Generated by Django 4.0.6 on 2022-08-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_set_exercise_id_set_routine_exercise_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='set_count',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='count',
        ),
    ]
