# Generated by Django 4.0.6 on 2022-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_set_count_set_count_remove_routine_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
