# Generated by Django 4.0.6 on 2022-08-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_alter_routineexercise_exercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineexercise',
            name='exercise_id',
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='exercise_name',
            field=models.ForeignKey(db_column='exercise_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='exercise.exercise', to_field='ko_name'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ko_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
