# Generated by Django 4.0.6 on 2022-08-17 16:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, default='default', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
