# Generated by Django 4.0.6 on 2022-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.TextField(),
        ),
    ]
