# Generated by Django 4.0.4 on 2022-09-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, default='default', null=True, upload_to=''),
        ),
    ]
