# Generated by Django 3.2.14 on 2022-09-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='record_day',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
