# Generated by Django 4.0.6 on 2022-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='likes',
            field=models.TextField(null=True),
        ),
    ]
