# Generated by Django 4.0.6 on 2022-09-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='likes',
        ),
    ]
