# Generated by Django 3.2.14 on 2022-08-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercise', '0003_alter_routine_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='creatorName',
        ),
        migrations.AddField(
            model_name='routine',
            name='creator_id',
            field=models.ForeignKey(blank=True, db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routine_creator', to='accounts.member'),
        ),
    ]
