# Generated by Django 4.0.6 on 2022-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_routine_origin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='origin_id',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
