# Generated by Django 4.0.4 on 2022-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
