# Generated by Django 4.0.4 on 2022-08-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_password_alter_member_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.ImageField(blank=True, default='default', null=True, upload_to='images/'),
        ),
    ]
