# Generated by Django 4.0.6 on 2022-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='liked_id',
            field=models.TextField(null=True),
        ),
    ]
