# Generated by Django 4.0.6 on 2022-09-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_liked_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='liked_id',
        ),
    ]
