# Generated by Django 4.0.6 on 2022-10-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_member_likes'),
        ('record', '0003_remove_record_liked_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='like_user',
            field=models.ManyToManyField(related_name='like_record', to='accounts.member'),
        ),
    ]
